version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_BASE_URL: http://localhost:5000
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
    ports:
      - "3000:80"
